# Generated by Django 3.1.4 on 2020-12-16 11:09

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('skillset', multiselectfield.db.fields.MultiSelectField(choices=[('java', 'java'), ('c++', 'c++'), ('python', 'python'), ('c#', 'c#'), ('php', 'php')], default='', max_length=22)),
                ('skill_1', models.CharField(default='', max_length=50)),
                ('skill_2', models.CharField(default='', max_length=50)),
                ('skill_3', models.CharField(default='', max_length=50)),
                ('skill_4', models.CharField(default='', max_length=50)),
                ('skill_5', models.CharField(default='', max_length=50)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
            ],
        ),
    ]
