# Generated by Django 3.1.2 on 2020-11-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='name',
        ),
    ]
