# Generated by Django 3.1.2 on 2020-11-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201102_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverletter',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
