# Generated by Django 3.1.2 on 2020-12-02 09:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201102_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='skillset',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'java'), ('item_key2', 'c++'), ('item_key3', 'python'), ('item_key4', 'c#'), ('item_key5', 'php')], default='', max_length=49),
        ),
    ]
