# Generated by Django 3.1.2 on 2020-12-02 10:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_skillset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='skillset',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('java', 'java'), ('c++', 'c++'), ('python', 'python'), ('c#', 'c#'), ('php', 'php')], default='', max_length=22),
        ),
    ]
